# settings!

[credentials]
bot_token = 'MzM1OTY2MzcxMjQwNDc2Njgz.DExcmw.GTIEPHAexF_7Iq0-OfeeoBkeR9s'
#bot_email = ''
#bot_password = ''

[owner]
owner_id = '335966371240476683'

[settings]
command_prefix = 'a3'
playing_text = 'with Python3.5'
playing_type = '1'

channel_id_bind = [
    '335918281615736834', #flightplan
    '335918709476687875', #afterhours
    ]
server_id_bind = [
    '335918281615736834', #antares_squadron
    ]